### ISSUE TITLE
Feature Request: Blu-ray, DVD and SD posters.

### ISSUE THREAD

**Issue by Zero0Q** [jkirkcaldy/plex-utills#91] opened 2022-01-05 03:30 UTC
Would you be able to add posters for media like Blu-ray, DVD and SD 
Like this:
![image](https://user-images.githubusercontent.com/20936968/148156253-7c83bc53-5838-41a3-860c-1e78485714b5.jpg)

**Comment by jkirkcaldy** [comment] 2022-01-05 10:31
Duplicate of #16

**Closed by jkirkcaldy** 2022-01-05 10:31 UTC
